W4D1/cats/config/routes.rb
Rails.application.routes.draw do

  resources :cats do
    # /cats/:cat_id/toys/:id
    # keep only the ones that don't reference a *specific* toy, otherwise the path is redundant
    resources :toys, only: [:index, :new]
  end
  # keep the ones that reference a specific toy, to keep path cleaner
  # /toys/:id
  resources :toys, only: [:create, :show, :update, :destroy]

  root to: redirect("/cats")
end

W4D1/cats/app/models/cat.rb
class Cat < ActiveRecord::Base
    validates :name, :skill, presence: true

    has_many :toys
end

W4D1/cats/app/models/toy.rb
class Toy < ActiveRecord::Base
    TYPES = [
        "string",
        "ball",
        "yarnball",
        "mouse"
    ]

    validates :cat_id, :name, :ttype, presence: true
    validates :ttype, inclusion: TYPES

    belongs_to :cat

end

W4D1/cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery prepend: true
end

W4D1/cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
	def index
		# GET /cats
		# render json: Cat.all  #show all the cats
		@cats = Cat.all
		render :index
	end

	def show 
		# GET /cats/123
		# render json: Cat.find(params[:id]) #show the cat for that ID
		@cat = Cat.find(params[:id])
		render :show
	end

	# Creating a cat with an invalid input
		# 1) Get /cats/new to fetch a form
		# 2) User fills out form incorrectly, clicks submit
		# 3) Validation fails
		# 4) Server renders "new" template again
		# 5) The form is filled in with @cat data

	def create
		@cat = Cat.new(cat_params)

		if @cat.save
			# cat_url(@cat) == /cat/{@cat.id}
			redirect_to cat_url(@cat)
		else
			render :new
			# render json: @cat.errors.full_messages, status: :unprocessable_entity
		end 
	end 

	# Creating a new cat is a multi-step process:dds
		# 1) Get /cats/new to fetch a form
		# 2) User fills out form, clicks submit
		# 3) POST /cats the data in the form
		# 4) Create action is invoked, cat is created
		# 5) Send client a redirect to /cats/#{id}
		# 6) Client makes a GET request for /cats/#{id}
		# 7) Show actions for newly created cat is invoked

	def new
		# /cats/new
		# show a form to create a new object
		@cat = Cat.new
		render :new
	end

	def update
		@cat = Cat.find(params[:id])
		if @cat.update(cat_params)
			redirect_to cat_url(@cat)
		else
			render :edit
		end
	end

	def edit
		# /cats/:id/edit
		# show a form to edit an existing object
		@cat = Cat.find(params[:id])
		render :edit
	end

	def destroy
		# DELETE /cats/:id
		cat = Cat.find(params[:id])
		cat.destroy
		redirect_to cats_url

		#1 Get /cats
		#2 Click delete buttom
		#3 Sends POST /cats/1; but _method="DELETE" so rails understands to destroy
		#4 Destroys the cat. Issues a redirect to the client.
		#5 Client GETS /cats again
	end

	private
	def cat_params
        params[:cat].permit(:name, :skill)
    end
end

W4D1/cats/app/controllers/toys_controller.rb
class ToysController < ApplicationController
    def index
        # /cats/:cat_id/toys
        cat = Cat.find(params[:cat_id])
        render json: cat.toys
    end

    def show
        # /cats/:cat_id/toys/:id    ==> redundant
        # /toys/:id                 ==> preferable, since you already need the toy_id
        render json: Toy.find(params[:id])
    end

    def create
        # POST /cats/:cat_id/toys
        # POST /toys
        @toy = Toy.new(toy_params)
        @cat = @toy.cat
        # toy.cat_id = params[:cat_id]

        if @toy.save
            redirect_to cat_url(@cat)
        else
            render :new
            # render json: toy.errors.full_messages, status: :unprocessable_entity
        end 
    end

    def destoy
        # /toys/:id 
        toy = Toy.find(params[:id])
        toy.destroy
        render json: toy
    end

    def edit
        
    end

    def update
        # /toys/:id 
         toy = Toy.find(params[:id])

         success = toy.update(toy_params)

         if success
            render json: toy
         else
            render  json: toy.errors.full_messages, status: :unprocessable_entity
         end
    end

    def new
        @cat = Cat.find(params[:cat_id])
        @toy = Toy.new
        render :new
    end
    private

    def toy_params
        params[:toy].permit(:cat_id, :name, :ttype)
    end
end

W4D1/cats/app/views/cats/_form.html.erb
<% action_url = cat.persisted? ? cat_url(cat) : cats_url %>
<% form_method = cat.persisted? ? "PATCH" : "POST"  %>
<% submit_text = cat.persisted? ? "Update Cat!" : "Create Cat!"%>

<form action="<%= action_url %>" method="POST">
    <input type="hidden" name="_method" value="<%= form_method %>">
    <label for="cat_name">Name</label>
    <input  type="text" 
            name="cat[name]" 
            id="cat_name"
            value="<%= @cat.name %>">
    <br>
    <label for="cat_skill">Skill</label>
    <input  type="text" 
            name="cat[skill]" 
            id="cat_skill"
            value="<%= @cat.skill %>">
    <br>

    <input type="submit" value="<%= submit_text %>">
</form>

W4D1/cats/app/views/cats/edit.html.erb
<h1> Update <%= @cat.name %></h1>

<!-- renders a partial -->
<%= render "form", cat: @cat %>

W4D1/cats/app/views/cats/index.html.erb
<h1> All the Cats!</h1>

<ul>
    <%# <li><%= ["this", "is", "cool"].join(", ")%>
    <% @cats.each do |cat| %>
        <li> 
            <a href="<%= cat_url(cat) %>"><%= cat.name %></a>
            <form action="<%= cat_url(cat) %>" method="POST">
                <input type="hidden" name="_method" value="DELETE">
                <input type="submit" value="Destroy Cat!"> 
            </form>
        </li>
    <% end %>
</ul>

<a href="<%= new_cat_url %>">New Cat!</a>

W4D1/cats/app/views/cats/new.html.erb
<h1> Build a new cat!</h1>

<!-- renders a partial -->
<%= render "form", cat: @cat %>

W4D1/cats/app/views/cats/show.html.erb
<h1> <%= @cat.name %> </h1>
<h2> Skills: </h2>
<ul>
    <li><%= @cat.skill %>
</ul>
 
<h2> Toys </h2>
<ul>
    <% @cat.toys.each do |toy| %>
        <li> 
            <a href="<%= toy_url(toy.id) %>"><%= toy.name %> </a>
        </li>
    <% end %>
</ul>

<h2> Other Useful Links </h2>
<ul>
    <li> <a href="<%= new_cat_toy_url(@cat) %>">Get me a new toy!</a></li>
    <li> <a href="<%= edit_cat_url(@cat) %>">Edit <%= @cat.name %>!</a></li>
    <li> <a href="<%= cats_url %>">Index</a> </li>
</ul>

<h2> Details </h2>
<pre>
    <%= @cat.to_json %>
</pre>

W4D1/cats/app/views/toys/new.html.erb
<h1><%= @cat.name %>'s New Toy!</h1>
    
    <form action="/toys" method="POST">
    <input type="hidden" name="toy[cat_id]" value="<%= @cat.id %>">


    <label for="toy_name">Name of Toy</label>
    <input 
        type="text" 
        name="toy[name]" 
        value="<%= @toy.name %>">
    <br>

    <label for="toy_type">Type of Toy</label>
    <select name="toy[ttype]" id="toy_ttype">
        <% Toy::TYPES.each do |type| %>
            <option value="<%= type %>"
                <%= "selected" if @toy.ttype == type %>>
                <%= type.upcase %>
            </option>
        <% end %>
    </select>

    <input type="submit" value="Create Toy!">

</form>